[package]
name = "casql"
version = "0.1.0"
authors = ["Michael Raymond <michael_raymond@fastmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
directories = "2.0.2"
postgres = { version = "0.15.2", features = ["with-chrono", "with-uuid", "with-serde_json"] }
serde = "1.0.103"
serde_json = "1.0.42"
serde_derive = "1.0.103"
toml = "0.5.5"
uuid = "0.5"

[dependencies.clap]
version = "3.0.0-beta.1"
default-features = false
features = [ "derive", "suggestions", "vec_map" ]

[patch.crates-io]
clap = { git = "https://github.com/clap-rs/clap.git" }
