[package]
name = "casql"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
itoa = "0.4.8"
md5 = "0.7.0"
serde = { version = "1.0.130", features = ["derive"] }
#serde_derive = "1.0.130"
serde_json = "1.0.68"
ryu = "1.0.5"


