[package]
name = "casql"
version = "0.1.0"
authors = ["Michael Raymond <michael_raymond@fastmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
postgres = { version = "0.15.2", features = ["with-chrono", "with-uuid", "with-serde_json"] }
serde = "1.0.103"
serde_json = "1.0.42"
chrono = "0.4"
uuid = "0.5"
