[package]
name = "casql"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
argh = "0.1.6"
md5 = "0.7.0"
serde = { version = "1.0.130", features = ["derive"] }
#serde_derive = "1.0.130"
serde_json = "1.0.68"
toml = "0.5.8"

